#
# Configuration
#

sudo: required
dist: trusty

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

branches:
  only:
    - master

#
# Build Lifecycle:
#

before_install:
  #- nvm use 4.2.6
  - npm install -g cordova ionic
  - ionic state restore
  - rm -rf node_modules

install: npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build                        # ionic build
  - npm run test                         # unit tests

after_failure:
  - cat /home/travis/build/koljagava/kRunning/ionic_serve.log

after_success:
  # Send coverage info off to cloud ppl
  #- cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # start install android
  - wget http://dl.google.com/android/android-sdk_r24.2-linux.tgz
  - tar -xzvf android-sdk_r24.2-linux.tgz
  - echo "y" | ./android-sdk-linux/tools/android update sdk --no-ui --filter android-23,build-tools-23.0.1
  - export ANDROID_HOME=${PWD}/android-sdk-linux
  # end install android
  - ionic state restore
  - ionic platform add android
  - ionic build android
  # `ionic build android` wraps `cordova build android`, which gives a legit exit code if it fails. Ionic does not; test apk exists.
  - ls ./platforms/android/build/outputs/apk/android*.apk

deploy:
# provider: script
#  script: .travis/deploy.sh
#skip_cleanup: true
